FROM ubuntu:16.04

RUN apt-get clean && \
    apt-get update && \
    apt-get install -y \
        software-properties-common && \
        python2.7 \
        curl \
        build-essential \
        libcurl4-openssl-dev \
        git \
        cmake \
        libssl-dev \
        uuid-dev \
        valgrind \
        libglib2.0-dev
        gdb \
        gdbserver \
        openssh-server

ENV PUB_KEY "{{publicKey}}"
